version: '3'
services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "~/.ivy2:/root/.ivy2"
      - "~/.sbt:/root/.sbt"
    depends_on:
      - rabbitServer
    tty: true

  rabbitServer:
    image: rabbitmq
    ports:
      - "5672:5672"
    command: "rabbitmq-server"